<?php
?>
<div data-role="devhub-fbeventtracker-subscribe" style="display:none;">
</div>
<span class="devhub-subscribe-email" style="display:none;"></span>
<span class="devhub-subscribe-id" style="display:none;"></span>
<script type="text/x-magento-init">
    {
        "[data-role='devhub-fbeventtracker-subscribe']":
            {
                "Magento_Ui/js/core/app": <?= $block->getJsLayout();?>
            }
    }
</script>
